spring:
  application:
    name: HostelBooking
  jpa:
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5435/hotelBooking
    username: postgres
    password: postgres
    hikari:
      schema: booking
      connection-init-sql: create schema if not exists booking
      connection-timeout: 10000

